"""initial migration

Revision ID: 20f4974182ea
Revises: 
Create Date: 2026-08-12 13:37:16.755597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f4974182ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_table_id'), 'example_table', ['id'], unique=False)
    op.create_index(op.f('ix_example_table_name'), 'example_table', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_table_name'), table_name='example_table')
    op.drop_index(op.f('ix_example_table_id'), table_name='example_table')
    op.drop_table('example_table')
    # ### end Alembic commands ###
