"""add_fusion_method

Revision ID: 895e6cc3c039
Revises: 75fedb3f3f74
Create Date: 2026-09-22 14:34:44.563193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895e6cc3c039'
down_revision: Union[str, Sequence[str], None] = '75fedb3f3f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_scans', sa.Column('fusion_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_scans', 'fusion_method')
    # ### end Alembic commands ###
