"""create_phishlens_tables

Revision ID: 95afd8a1f909
Revises: 20f4974182ea
Create Date: 2026-08-12 13:41:19.273861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95afd8a1f909'
down_revision: Union[str, Sequence[str], None] = '20f4974182ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('final_risk_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_scans_id'), 'url_scans', ['id'], unique=False)
    op.create_index(op.f('ix_url_scans_url'), 'url_scans', ['url'], unique=False)
    op.create_table('domain_intelligence_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('domain_age_days', sa.Integer(), nullable=True),
    sa.Column('registrar', sa.String(), nullable=True),
    sa.Column('ssl_valid', sa.Boolean(), nullable=True),
    sa.Column('ssl_issuer', sa.String(), nullable=True),
    sa.Column('dnssec_enabled', sa.Boolean(), nullable=True),
    sa.Column('domain_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['url_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_index(op.f('ix_domain_intelligence_results_id'), 'domain_intelligence_results', ['id'], unique=False)
    op.create_table('heuristic_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('url_length', sa.Integer(), nullable=True),
    sa.Column('dot_count', sa.Integer(), nullable=True),
    sa.Column('hyphen_count', sa.Integer(), nullable=True),
    sa.Column('digit_count', sa.Integer(), nullable=True),
    sa.Column('special_char_count', sa.Integer(), nullable=True),
    sa.Column('entropy_score', sa.Float(), nullable=True),
    sa.Column('has_suspicious_keywords', sa.Boolean(), nullable=True),
    sa.Column('lexical_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['url_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_index(op.f('ix_heuristic_results_id'), 'heuristic_results', ['id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['url_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_table('page_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('has_login_form', sa.Boolean(), nullable=True),
    sa.Column('has_hidden_iframe', sa.Boolean(), nullable=True),
    sa.Column('has_js_redirect', sa.Boolean(), nullable=True),
    sa.Column('behavior_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['url_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_index(op.f('ix_page_analysis_id'), 'page_analysis', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['url_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('threat_intelligence_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('detections', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['url_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_results_id'), 'threat_intelligence_results', ['id'], unique=False)
    op.drop_index(op.f('ix_example_table_id'), table_name='example_table')
    op.drop_index(op.f('ix_example_table_name'), table_name='example_table')
    op.drop_table('example_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('example_table_pkey'))
    )
    op.create_index(op.f('ix_example_table_name'), 'example_table', ['name'], unique=False)
    op.create_index(op.f('ix_example_table_id'), 'example_table', ['id'], unique=False)
    op.drop_index(op.f('ix_threat_intelligence_results_id'), table_name='threat_intelligence_results')
    op.drop_table('threat_intelligence_results')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_page_analysis_id'), table_name='page_analysis')
    op.drop_table('page_analysis')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_heuristic_results_id'), table_name='heuristic_results')
    op.drop_table('heuristic_results')
    op.drop_index(op.f('ix_domain_intelligence_results_id'), table_name='domain_intelligence_results')
    op.drop_table('domain_intelligence_results')
    op.drop_index(op.f('ix_url_scans_url'), table_name='url_scans')
    op.drop_index(op.f('ix_url_scans_id'), table_name='url_scans')
    op.drop_table('url_scans')
    # ### end Alembic commands ###
