"""add_punycode_homoglyph_to_heuristic_results

Revision ID: d24e5aaf11a5
Revises: dd715316919d
Create Date: 2026-08-22 14:28:52.727086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24e5aaf11a5'
down_revision: Union[str, Sequence[str], None] = 'dd715316919d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heuristic_results', sa.Column('has_punycode_or_homoglyph', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heuristic_results', 'has_punycode_or_homoglyph')
    # ### end Alembic commands ###
