"""add_behavior_columns_to_page_analysis

Revision ID: dd715316919d
Revises: af0393060f73
Create Date: 2026-08-22 11:25:30.784886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd715316919d'
down_revision: Union[str, Sequence[str], None] = 'af0393060f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_analysis', sa.Column('external_form_action', sa.Boolean(), nullable=True))
    op.add_column('page_analysis', sa.Column('popup_detected', sa.Boolean(), nullable=True))
    op.add_column('page_analysis', sa.Column('behavior_analysis_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_analysis', 'behavior_analysis_failed')
    op.drop_column('page_analysis', 'popup_detected')
    op.drop_column('page_analysis', 'external_form_action')
    # ### end Alembic commands ###
